//
// Created by hgtll on 19/03/2023.
//

#ifndef PARSER_H
#define PARSER_H

#define N_STATES 56
#define N_PRODUCTIONS 24
#define TERMINAL_SIZE 13

typedef enum {
    programa,
    corpo,
    declara,
    mais_dc,
    cont_dc,
    dvar,
    variaveis,
    mais_var,
    rotina,
    procedimento,
    funcao,
    parametros,
    lista_parametros,
    cont_lista_par,
    lista_id,
    cont_lista_id,
    NON_TERMINAL_SIZE
} NonTerminal;

typedef enum {
    SHIFT,
    REDUCE,
    ACCEPT,
    ERROR
} Action;

typedef struct {
    int id;
    Action action;
} TableEntry;

typedef struct {
    int rightSize;
    NonTerminal left;
} Production;

Production productions[N_PRODUCTIONS] = {{.left = programa, .rightSize = 4},
                                         {.left = corpo, .rightSize = 4},
                                         {.left = declara, .rightSize = 3},
                                         {.left = declara, .rightSize = 0},
                                         {.left = mais_dc, .rightSize = 2},
                                         {.left = cont_dc, .rightSize = 3},
                                         {.left = cont_dc, .rightSize = 0},
                                         {.left = dvar, .rightSize = 3},
                                         {.left = variaveis, .rightSize = 2},
                                         {.left = mais_var, .rightSize = 2},
                                         {.left = mais_var, .rightSize = 0},
                                         {.left = rotina, .rightSize = 1},
                                         {.left = rotina, .rightSize = 1},
                                         {.left = rotina, .rightSize = 0},
                                         {.left = procedimento, .rightSize = 7},
                                         {.left = funcao, .rightSize = 9},
                                         {.left = parametros, .rightSize = 3},
                                         {.left = parametros, .rightSize = 0},
                                         {.left = lista_parametros, .rightSize = 4},
                                         {.left = cont_lista_par, .rightSize = 2},
                                         {.left = cont_lista_par, .rightSize = 0},
                                         {.left = lista_id, .rightSize = 2},
                                         {.left = cont_lista_id, .rightSize = 2},
                                         {.left = cont_lista_id, .rightSize = 0}};

TableEntry actionTable[N_STATES][TERMINAL_SIZE] = {{{.action = SHIFT, .id = 2},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ACCEPT, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 3},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 4},   {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 7},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 4},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 4}, {.action = REDUCE, .id = 4}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 14}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 12}, {.action = SHIFT, .id = 11}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 15}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = SHIFT, .id = 16},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 12}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 13}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 17}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 18}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 20},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 21},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = SHIFT, .id = 23}, {.action = REDUCE, .id = 11}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = SHIFT, .id = 24}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 18}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 18}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 26}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 18}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 26}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 3},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 3}, {.action = REDUCE, .id = 3}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 29}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 7},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 7}, {.action = REDUCE, .id = 7}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 30}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 9},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 15}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 2},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 2}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 32},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 35}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 36},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 5},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 5}, {.action = REDUCE, .id = 5}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 15}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 8},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 10}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 38}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 39},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 40},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = SHIFT, .id = 42}, {.action = REDUCE, .id = 24}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 7},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 4},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 4}, {.action = REDUCE, .id = 4}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 20},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 45},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 17}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 17}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 46}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 22}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 35}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 48},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 6},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 6}, {.action = REDUCE, .id = 6}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = SHIFT, .id = 7},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 4},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 4}, {.action = REDUCE, .id = 4}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 51},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 21}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 23}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 14}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 12}, {.action = SHIFT, .id = 11}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 53},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 19}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = SHIFT, .id = 35}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 15}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 14}, {.action = ERROR, .id = -1}, {.action = SHIFT, .id = 12}, {.action = SHIFT, .id = 11}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = REDUCE, .id = 20}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}},
                                                   {{.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = REDUCE, .id = 16}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1},  {.action = ERROR, .id = -1}, {.action = ERROR, .id = -1}}};

int goTable[N_STATES][NON_TERMINAL_SIZE] = {{1,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, 5,  6,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, 8,  9,  10, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, 13, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, 19, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, 22, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 25, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 27, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, 31, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 33, -1, 34, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, 37, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 41},
                                            {-1, 43, 6,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, 44, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 47, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, 49, 6,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 50, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, 52, 9,  10, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 54, -1, 34, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, 55, 9,  10, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
                                            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}};

#endif //COMPILER_BOOK_PARSER_H
