all: grammar1 grammar2 grammar5

grammar1: build
	gcc -Wall src/grammar1.c -o build/grammar1

grammar2: build
	gcc -Wall src/grammar2.c -o build/grammar2

grammar5: build
	gcc -Wall src/grammar5.c -o build/grammar5

build:
	mkdir build